name: tiktoken_tokenizer_gpt4o_o1
description: "OpenAI's Tiktoken tokenizer for models: GPT-4, GPT-4o, GPT-4o-mini, o1, o1-mini, and o1-preview."
version: 1.0.0
homepage: https://github.com/marcglasberg/tiktoken_tokenizer_gpt4o_o1

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
